### ISSUE TITLE
davidji99/bitbucket-go version changes

### ISSUE THREAD

**Issue by SiqingYu** [deps-cloud/discovery#22]
https://github.com/davidji99/bitbucket-go has changed its releases. 
`github.com/davidji99/go-bitbucket v0.5.0` is no longer available for new builds.

**Comment by mjpitz** [comment]
@SiqingYu : I noticed that. Definitely need to update this repo. I have some motivation to work on this end of the process some more. Feel free to submit a PR in the meantime.

**Comment by mjpitz** [comment]
PR: https://github.com/deps-cloud/discovery/pull/23
